CREATE DATABASE IF NOT EXISTS BD_EST_SUPER;
USE BD_EST_SUPER;

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INT PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
    TIPO VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTO(
	ID INT  AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
    VALIDADE DATE,
    FK_CATEGORIA_ID INT
);

CREATE TABLE IF NOT EXISTS FORNECEDOR(
	CPF_CNPJ VARCHAR(14) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(11) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTO_FORNECEDOR(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    FK_PRODUTO_ID INT,
    FK_FORNECEDOR_CPF_CNPJ VARCHAR(14)
);


