CREATE DATABASE IF NOT EXISTS BD_MUSICA;
USE BD_MUSICA;

CREATE TABLE IF NOT EXISTS ARTISTA(
	CPF VARCHAR(11) PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
    TELEFONE VARCHAR(9) NOT NULL
);

CREATE TABLE IF NOT EXISTS GENERO(
	ID INT PRIMARY KEY,
    ESTILO VARCHAR(50) NOT NULL,
    RITMO VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS ALBUM(
	ID INT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    TEMPO TIMESTAMP NOT NULL,
    FK_ARTISTA_CPF INT 
);

CREATE TABLE IF NOT EXISTS FAIXA(
	ID INT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DURACAO_TEMPO TIMESTAMP,
    FK_GENERO_ID INT,
    FK_FAIXA_ID INT
);

